#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-apache-log4j-extras
Version  : 1.2.17
Release  : 1
URL      : https://repo1.maven.org/maven2/log4j/apache-log4j-extras/1.2.17/apache-log4j-extras-1.2.17.jar
Source0  : https://repo1.maven.org/maven2/log4j/apache-log4j-extras/1.2.17/apache-log4j-extras-1.2.17.jar
Source1  : https://repo1.maven.org/maven2/log4j/apache-log4j-extras/1.2.17/apache-log4j-extras-1.2.17.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-apache-log4j-extras-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-apache-log4j-extras package.
Group: Data

%description data
data components for the mvn-apache-log4j-extras package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/log4j/apache-log4j-extras/1.2.17
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/log4j/apache-log4j-extras/1.2.17

mkdir -p %{buildroot}/usr/share/java/.m2/repository/log4j/apache-log4j-extras/1.2.17
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/log4j/apache-log4j-extras/1.2.17


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/log4j/apache-log4j-extras/1.2.17/apache-log4j-extras-1.2.17.jar
/usr/share/java/.m2/repository/log4j/apache-log4j-extras/1.2.17/apache-log4j-extras-1.2.17.pom
